/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUILayer;

/**
 *
 * @author domino54
 */
public class TrainControllerPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrainControllerPanel
     */
    public TrainControllerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vSetPoint_slide = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        desiredTemp_slide = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        eBrake_on = new javax.swing.JToggleButton();
        eBrake_off = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        sBrake_on = new javax.swing.JToggleButton();
        sBrake_off = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        extLights_on = new javax.swing.JToggleButton();
        extLights_off = new javax.swing.JToggleButton();
        intLights_off = new javax.swing.JToggleButton();
        intLights_on = new javax.swing.JToggleButton();
        lDoors_close = new javax.swing.JToggleButton();
        lDoors_open = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rDoors_open = new javax.swing.JToggleButton();
        rDoors_close = new javax.swing.JToggleButton();
        eBrake_status = new javax.swing.JLabel();
        sBrake_status = new javax.swing.JLabel();
        rDoors_status = new javax.swing.JLabel();
        lDoors_status = new javax.swing.JLabel();
        intLights_status = new javax.swing.JLabel();
        extLights_status = new javax.swing.JLabel();
        vSetPoint_status = new javax.swing.JLabel();
        desiredTemp_status = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        powerOutput_txt = new javax.swing.JTextArea();

        jLabel1.setText("V Set Point");

        vSetPoint_slide.setMaximum(19440);
        vSetPoint_slide.setValue(0);

        jLabel2.setText("Desired Temp");

        desiredTemp_slide.setMaximum(85);
        desiredTemp_slide.setMinimum(40);
        desiredTemp_slide.setValue(72);

        jLabel3.setText("E. Brake");

        eBrake_on.setText("Engage");

        eBrake_off.setText("Disengage");

        jLabel4.setText("S. Brake");

        sBrake_on.setText("Engage");

        sBrake_off.setText("Disengage");

        jLabel5.setText("Int. Lights");

        jLabel6.setText("Ext. Lights");

        extLights_on.setText("On");

        extLights_off.setText("Off");

        intLights_off.setText("Off");

        intLights_on.setText("On");

        lDoors_close.setText("Close");

        lDoors_open.setText("Open");

        jLabel7.setText("L Doors");

        jLabel8.setText("R Doors");

        rDoors_open.setText("Open");

        rDoors_close.setText("Close");

        eBrake_status.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        eBrake_status.setText("AUTO");

        sBrake_status.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        sBrake_status.setText("AUTO");

        rDoors_status.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        rDoors_status.setText("AUTO");

        lDoors_status.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lDoors_status.setText("AUTO");

        intLights_status.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        intLights_status.setText("AUTO");

        extLights_status.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        extLights_status.setText("AUTO");

        vSetPoint_status.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        vSetPoint_status.setText("0 mph");

        desiredTemp_status.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        desiredTemp_status.setText("72 F");

        jLabel9.setText("Power Output");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        powerOutput_txt.setEditable(false);
        powerOutput_txt.setColumns(20);
        powerOutput_txt.setRows(1);
        powerOutput_txt.setEnabled(false);
        jScrollPane1.setViewportView(powerOutput_txt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(intLights_on)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(intLights_off)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(intLights_status))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(vSetPoint_slide, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(desiredTemp_slide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vSetPoint_status))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(334, 334, 334)
                                .addComponent(desiredTemp_status)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rDoors_open)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rDoors_close)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rDoors_status))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lDoors_open)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lDoors_close)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lDoors_status))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eBrake_on)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eBrake_off)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eBrake_status))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sBrake_on)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sBrake_off)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sBrake_status))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(extLights_on)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(extLights_off)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(extLights_status)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vSetPoint_slide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(eBrake_on)
                                        .addComponent(eBrake_off)
                                        .addComponent(eBrake_status)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(desiredTemp_slide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(sBrake_on)
                                .addComponent(sBrake_off)
                                .addComponent(sBrake_status)
                                .addComponent(desiredTemp_status))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vSetPoint_status)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(intLights_on)
                            .addComponent(intLights_off)
                            .addComponent(intLights_status))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(extLights_on)
                            .addComponent(extLights_off)
                            .addComponent(extLights_status)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(rDoors_open)
                            .addComponent(rDoors_close)
                            .addComponent(rDoors_status))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lDoors_open)
                            .addComponent(lDoors_close)
                            .addComponent(lDoors_status))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider desiredTemp_slide;
    private javax.swing.JLabel desiredTemp_status;
    private javax.swing.JToggleButton eBrake_off;
    private javax.swing.JToggleButton eBrake_on;
    private javax.swing.JLabel eBrake_status;
    private javax.swing.JToggleButton extLights_off;
    private javax.swing.JToggleButton extLights_on;
    private javax.swing.JLabel extLights_status;
    private javax.swing.JToggleButton intLights_off;
    private javax.swing.JToggleButton intLights_on;
    private javax.swing.JLabel intLights_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton lDoors_close;
    private javax.swing.JToggleButton lDoors_open;
    private javax.swing.JLabel lDoors_status;
    private javax.swing.JTextArea powerOutput_txt;
    private javax.swing.JToggleButton rDoors_close;
    private javax.swing.JToggleButton rDoors_open;
    private javax.swing.JLabel rDoors_status;
    private javax.swing.JToggleButton sBrake_off;
    private javax.swing.JToggleButton sBrake_on;
    private javax.swing.JLabel sBrake_status;
    private javax.swing.JSlider vSetPoint_slide;
    private javax.swing.JLabel vSetPoint_status;
    // End of variables declaration//GEN-END:variables
}
