/******************************************************************************
 * 
 * WaysidePanel class
 * 
 * Developed by AJility
 * April 2014
 * 
 * Contributers:
 *  Nathan Hachten
 * 
 * DISCLAIMER:
 *   This document contains un-editable code generated by NetBeans.  Due to this
 *  un-editable code, this document does not follow the AJility coding standard.
 *
 *****************************************************************************/

package GUILayer.Wayside;

import DataLayer.Wayside.TrackController;
import DataLayer.Wayside.Wayside;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class WaysidePanel extends javax.swing.JPanel {
    Wayside wayside;
    /**
     * Creates new form WaysidePanel
     */
    public WaysidePanel() {
        initComponents();
    }
    
    public void setMode(int mode) // 0 - manual, 1 - auto
    {
        if (mode == 0)
        {
            this.trackControllerPanel1.setEnabled(true); //should be false
            this.loadPLCButton.setEnabled(true); //should be false
        }
        else if (mode == 1)
        {
            this.trackControllerPanel1.setEnabled(true);
            this.loadPLCButton.setEnabled(true);
        }
    }
    
    public void setWayside(Wayside wayside)
    {
        this.wayside = wayside;
        for (TrackController tc : wayside.getControllers())
        {
            this.pLCTestPanel1.addController(tc);
           
        }
        reInitComponents();
    }
    
    private void reInitComponents()
    {
         controllerSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel(wayside.getControllerNames()));
         setControllers();
    }
    
    private void setControllers()
    {
        int index = this.controllerSelectComboBox.getSelectedIndex();
         this.trackControllerPanel1.SetController(this.wayside.getController(index));
         this.pLCTestPanel1.selectController(index);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controllerRadioGroup = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        controllerSelectComboBox = new javax.swing.JComboBox();
        pLCTestPanel1 = new GUILayer.Wayside.PLCTestPanel();
        trackControllerPanel1 = new GUILayer.Wayside.TrackControllerPanel();
        jLabel1 = new javax.swing.JLabel();
        plcVersionDisplay = new javax.swing.JLabel();
        loadPLCButton = new javax.swing.JButton();

        jLabel5.setText("Track Controllers");

        controllerSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        controllerSelectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controllerSelectComboBoxActionPerformed(evt);
            }
        });

        pLCTestPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Current PLC:");

        plcVersionDisplay.setText("Default");

        loadPLCButton.setText("Load PLC");
        loadPLCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadPLCButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(controllerSelectComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(plcVersionDisplay))
                                    .addComponent(jLabel1)))
                            .addComponent(loadPLCButton))
                        .addGap(18, 18, 18)
                        .addComponent(trackControllerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(pLCTestPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(controllerSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plcVersionDisplay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadPLCButton))
                    .addComponent(trackControllerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(pLCTestPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void controllerSelectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controllerSelectComboBoxActionPerformed
        // TODO add your handling code here:
        setControllers();
    }//GEN-LAST:event_controllerSelectComboBoxActionPerformed

    private void loadPLCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadPLCButtonActionPerformed
        // TODO add your handling code here:
        Object[] plcVersions = {"Default", "Version1", "Version2"};
        String s = (String)JOptionPane.showInputDialog(null, "Select the PLC program desired",
                                                        "PLC", JOptionPane.QUESTION_MESSAGE, null,
                                                        plcVersions, "Default");
        
        if (s!= null && s.length() > 0)
        {
            this.plcVersionDisplay.setText(s);
        }
        
        this.trackControllerPanel1.updatePLC(s);
        this.pLCTestPanel1.updatePLC(s);
               
    }//GEN-LAST:event_loadPLCButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup controllerRadioGroup;
    private javax.swing.JComboBox controllerSelectComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loadPLCButton;
    private GUILayer.Wayside.PLCTestPanel pLCTestPanel1;
    private javax.swing.JLabel plcVersionDisplay;
    private GUILayer.Wayside.TrackControllerPanel trackControllerPanel1;
    // End of variables declaration//GEN-END:variables
}
