/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUILayer.TrainModel;

import DataLayer.Train.TrainModel.PhysicsEngine;
import DataLayer.Train.TrainModel.TrainState;

/**
 *
 * @author drewwinfield
 */
public class TMInput extends javax.swing.JPanel {

    private PhysicsEngine physicsEngine;
    private TrainState trainState;
    
    /**
     * Creates new form PhysicsDisplay
     */
    public TMInput() {
        initComponents();
    }

    public void setPhysicsEngine(PhysicsEngine e)
    {
        physicsEngine = e;
    }
    
    public void setTrainState(TrainState s)
    {
        trainState = s;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputsLabel = new javax.swing.JLabel();
        temperatureInputLabel = new javax.swing.JLabel();
        faultInputLabel = new javax.swing.JLabel();
        temperatureInputTextField = new javax.swing.JTextField();
        temperatureInputApplyButton = new javax.swing.JButton();
        degreesFahLabel = new javax.swing.JLabel();
        engineFaultInputCheckBox = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        eBrakeRequestButton = new javax.swing.JToggleButton();
        eBrakeRequestLabel = new javax.swing.JLabel();

        inputsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputsLabel.setText("Inputs");

        temperatureInputLabel.setText("Temperature");

        faultInputLabel.setText("Fault");

        temperatureInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureInputTextFieldActionPerformed(evt);
            }
        });

        temperatureInputApplyButton.setText("Apply");
        temperatureInputApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureInputApplyButtonActionPerformed(evt);
            }
        });

        degreesFahLabel.setText("ºF");

        engineFaultInputCheckBox.setText("Engine Failure");

        jCheckBox1.setText("Signal Failure");

        jCheckBox2.setText("Service Brake Failure");

        jCheckBox3.setText("Emergency Brake Failure");

        eBrakeRequestButton.setText("Request");
        eBrakeRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBrakeRequestButtonActionPerformed(evt);
            }
        });

        eBrakeRequestLabel.setText("Passenger EBrake Request");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temperatureInputLabel)
                    .addComponent(faultInputLabel)
                    .addComponent(eBrakeRequestLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(temperatureInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(degreesFahLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(temperatureInputApplyButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eBrakeRequestButton)
                            .addComponent(jCheckBox1)
                            .addComponent(engineFaultInputCheckBox)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(inputsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temperatureInputLabel)
                    .addComponent(temperatureInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperatureInputApplyButton)
                    .addComponent(degreesFahLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faultInputLabel)
                    .addComponent(engineFaultInputCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eBrakeRequestButton)
                    .addComponent(eBrakeRequestLabel))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void temperatureInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperatureInputTextFieldActionPerformed

    private void temperatureInputApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureInputApplyButtonActionPerformed
        int newTemp = Integer.parseInt(temperatureInputTextField.getText());
        trainState.setTemperature(newTemp);
    }//GEN-LAST:event_temperatureInputApplyButtonActionPerformed

    private void eBrakeRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBrakeRequestButtonActionPerformed
        
    }//GEN-LAST:event_eBrakeRequestButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel degreesFahLabel;
    private javax.swing.JToggleButton eBrakeRequestButton;
    private javax.swing.JLabel eBrakeRequestLabel;
    private javax.swing.JCheckBox engineFaultInputCheckBox;
    private javax.swing.JLabel faultInputLabel;
    private javax.swing.JLabel inputsLabel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JButton temperatureInputApplyButton;
    private javax.swing.JLabel temperatureInputLabel;
    private javax.swing.JTextField temperatureInputTextField;
    // End of variables declaration//GEN-END:variables
}
