/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUILayer.TrainModel;
import DataLayer.Train.*;
import DataLayer.Train.TrainModel.*;
import java.text.DecimalFormat;

/**
 *
 * @author drewwinfield
 */
public class TMOutput extends javax.swing.JPanel {

    private PhysicsEngine physicsEngine;
    private TrainState trainState;
    private DecimalFormat df;
    
    /**
     * Creates new form StateDisplay
     */
    public TMOutput() {
        initComponents();
        df = new DecimalFormat("##.#");
    }

    public void setPhysicsEngine(PhysicsEngine e)
    {
        physicsEngine = e;
    }
    
    public void setTrainState(TrainState s)
    {
        trainState = s;
    }
    
    public void update()
    {
        double velocity = physicsEngine.getVelocity();
        boolean sBrake = physicsEngine.getServiceBrake();
        boolean eBrake = physicsEngine.getEmergencyBrake();
        boolean lDoor = trainState.getLeftDoors();
        boolean rDoor = trainState.getRightDoors();
        boolean extLights = trainState.getExteriorLights();
        boolean intLights = trainState.getInteriorLights();
        boolean heater = trainState.getHeater();
        
        velocity = velocity * 2.23694; // conversion from m/s to mph
        velocityDisplayBox.setText(df.format(velocity));
        
        if (sBrake)
        {
            sBrakeDisplayBox.setText("ON");
        }
        else
        {
            sBrakeDisplayBox.setText("OFF");
        }
        
        if (eBrake)
        {
            eBrakeDisplayBox.setText("ON");
        }
        else
        {
            eBrakeDisplayBox.setText("OFF");
        }
         
        if (lDoor)
        {
            leftDoorDisplayBox.setText("OPEN");
        }
        else
        {
            leftDoorDisplayBox.setText("CLOSED");
        }
        
         
        if (rDoor)
        {
            rightDoorDisplayBox.setText("OPEN");
        }
        else
        {
            rightDoorDisplayBox.setText("CLOSED");
        }
        
        if (intLights)
        {
            intLightsDisplayBox.setText("ON");
        }
        else
        {
            intLightsDisplayBox.setText("OFF");
        }
        
        if (extLights)
        {
            extLightsDisplayBox.setText("ON");
        }
        else
        {
            extLightsDisplayBox.setText("OFF");
        }

        if (heater)
        {
            heaterDisplayBox.setText("ON");
        }
        else
        {
            heaterDisplayBox.setText("OFF");
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outputsLabel = new javax.swing.JLabel();
        velocityOutputLabel = new javax.swing.JLabel();
        rightDoorOutputLabel = new javax.swing.JLabel();
        eBrakeOutputLabel = new javax.swing.JLabel();
        sBrakeOutputLabel = new javax.swing.JLabel();
        exteriorLightsOutputLabel = new javax.swing.JLabel();
        leftDoorOutputLabel = new javax.swing.JLabel();
        interiorLightsOutputLabel = new javax.swing.JLabel();
        mphLabel = new javax.swing.JLabel();
        sBrakeDisplayBox = new javax.swing.JTextField();
        eBrakeDisplayBox = new javax.swing.JTextField();
        rightDoorDisplayBox = new javax.swing.JTextField();
        leftDoorDisplayBox = new javax.swing.JTextField();
        intLightsDisplayBox = new javax.swing.JTextField();
        extLightsDisplayBox = new javax.swing.JTextField();
        velocityDisplayBox = new javax.swing.JTextField();
        heaterOutputLabel = new javax.swing.JLabel();
        heaterDisplayBox = new javax.swing.JTextField();

        outputsLabel.setText("Outputs");

        velocityOutputLabel.setText("Velocity");

        rightDoorOutputLabel.setText("Door open/close (Right side) \u0000");

        eBrakeOutputLabel.setText("Emergency Brake");

        sBrakeOutputLabel.setText("Service Brake");

        exteriorLightsOutputLabel.setText("Lights on/off (Exterior) \u0000");

        leftDoorOutputLabel.setText("Door open/close (Left side) \u0000");

        interiorLightsOutputLabel.setText("Lights on/off (Interior) \u0000");

        mphLabel.setText("mph");

        sBrakeDisplayBox.setText("Off");

        eBrakeDisplayBox.setText("Off");

        rightDoorDisplayBox.setText("Closed");

        leftDoorDisplayBox.setText("Closed");

        intLightsDisplayBox.setText("Off");

        extLightsDisplayBox.setText("Off");

        velocityDisplayBox.setText("0");

        heaterOutputLabel.setText("Heater");

        heaterDisplayBox.setText("Off");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(velocityOutputLabel)
                    .addComponent(interiorLightsOutputLabel)
                    .addComponent(leftDoorOutputLabel)
                    .addComponent(rightDoorOutputLabel)
                    .addComponent(exteriorLightsOutputLabel)
                    .addComponent(sBrakeOutputLabel)
                    .addComponent(eBrakeOutputLabel)
                    .addComponent(heaterOutputLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(outputsLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(velocityDisplayBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mphLabel))
                    .addComponent(sBrakeDisplayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eBrakeDisplayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightDoorDisplayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftDoorDisplayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intLightsDisplayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extLightsDisplayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heaterDisplayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputsLabel)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(velocityOutputLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mphLabel)
                        .addComponent(velocityDisplayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sBrakeOutputLabel)
                    .addComponent(sBrakeDisplayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eBrakeOutputLabel)
                    .addComponent(eBrakeDisplayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightDoorOutputLabel)
                    .addComponent(rightDoorDisplayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftDoorOutputLabel)
                    .addComponent(leftDoorDisplayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interiorLightsOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intLightsDisplayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exteriorLightsOutputLabel)
                    .addComponent(extLightsDisplayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heaterDisplayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heaterOutputLabel))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eBrakeDisplayBox;
    private javax.swing.JLabel eBrakeOutputLabel;
    private javax.swing.JTextField extLightsDisplayBox;
    private javax.swing.JLabel exteriorLightsOutputLabel;
    private javax.swing.JTextField heaterDisplayBox;
    private javax.swing.JLabel heaterOutputLabel;
    private javax.swing.JTextField intLightsDisplayBox;
    private javax.swing.JLabel interiorLightsOutputLabel;
    private javax.swing.JTextField leftDoorDisplayBox;
    private javax.swing.JLabel leftDoorOutputLabel;
    private javax.swing.JLabel mphLabel;
    private javax.swing.JLabel outputsLabel;
    private javax.swing.JTextField rightDoorDisplayBox;
    private javax.swing.JLabel rightDoorOutputLabel;
    private javax.swing.JTextField sBrakeDisplayBox;
    private javax.swing.JLabel sBrakeOutputLabel;
    private javax.swing.JTextField velocityDisplayBox;
    private javax.swing.JLabel velocityOutputLabel;
    // End of variables declaration//GEN-END:variables
}
