/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUILayer.CTC;

/**
 *
 * @author micha_000
 */
public class Manual extends javax.swing.JPanel {

    /**
     * Creates new form Manual
     */
    public Manual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blockClosingsRadioGroup = new javax.swing.ButtonGroup();
        switchPositionRadioGroup = new javax.swing.ButtonGroup();
        blockClosingsPanel = new javax.swing.JPanel();
        blockClosingsLineDrop = new javax.swing.JComboBox();
        blockClosingsSectionDrop = new javax.swing.JComboBox();
        blockClosingsBlockDrop = new javax.swing.JComboBox();
        blockClosingsCloseRadio = new javax.swing.JRadioButton();
        blockClosingsOpenRadio = new javax.swing.JRadioButton();
        blockClosingsSubmitButton = new javax.swing.JButton();
        blockClosingsLabel = new javax.swing.JLabel();
        routeTrainPanel = new javax.swing.JPanel();
        routeTrainLabel = new javax.swing.JLabel();
        routeTrainAuthorityLabel = new javax.swing.JLabel();
        routeTrainAuthorityValueLabel = new javax.swing.JLabel();
        routeTrainSpeedText = new javax.swing.JTextField();
        routeTrainsBlockDrop = new javax.swing.JComboBox();
        routeTrainTrainDrop = new javax.swing.JComboBox();
        routeTrainLineDrop = new javax.swing.JComboBox();
        routeTrainSectionDrop = new javax.swing.JComboBox();
        routeTrainSubmitButton = new javax.swing.JButton();
        routeTrainSpeedLabel = new javax.swing.JLabel();
        switchPositionsPanel = new javax.swing.JPanel();
        switchPositionSubmitButton = new javax.swing.JButton();
        switchPositionLineDrop = new javax.swing.JComboBox();
        switchPositionSwitchesDrop = new javax.swing.JComboBox();
        switchPositionsDivergentRadio = new javax.swing.JRadioButton();
        switchPositionLabel = new javax.swing.JLabel();
        switchPositionsStraightRadio = new javax.swing.JRadioButton();

        blockClosingsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        blockClosingsLineDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Line", "Green", "Red" }));
        blockClosingsLineDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockClosingsLineDropActionPerformed(evt);
            }
        });

        blockClosingsSectionDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Section" }));

        blockClosingsBlockDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Block #" }));

        blockClosingsRadioGroup.add(blockClosingsCloseRadio);
        blockClosingsCloseRadio.setText("Close");

        blockClosingsRadioGroup.add(blockClosingsOpenRadio);
        blockClosingsOpenRadio.setText("Open");

        blockClosingsSubmitButton.setText("Submit");

        blockClosingsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        blockClosingsLabel.setText("Block Closings");

        javax.swing.GroupLayout blockClosingsPanelLayout = new javax.swing.GroupLayout(blockClosingsPanel);
        blockClosingsPanel.setLayout(blockClosingsPanelLayout);
        blockClosingsPanelLayout.setHorizontalGroup(
            blockClosingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blockClosingsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(blockClosingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(blockClosingsOpenRadio)
                    .addComponent(blockClosingsBlockDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(blockClosingsCloseRadio)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blockClosingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blockClosingsLineDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blockClosingsSectionDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(blockClosingsPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(blockClosingsLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(blockClosingsPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(blockClosingsSubmitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        blockClosingsPanelLayout.setVerticalGroup(
            blockClosingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockClosingsPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(blockClosingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blockClosingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blockClosingsLineDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockClosingsSectionDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(blockClosingsBlockDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(blockClosingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blockClosingsCloseRadio)
                    .addComponent(blockClosingsOpenRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(blockClosingsSubmitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        routeTrainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        routeTrainLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        routeTrainLabel.setText("Route Trains");

        routeTrainAuthorityLabel.setText("Authority:");

        routeTrainAuthorityValueLabel.setText("0");

        routeTrainSpeedText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeTrainSpeedTextActionPerformed(evt);
            }
        });

        routeTrainsBlockDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Block #" }));

        routeTrainTrainDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Train #" }));
        routeTrainTrainDrop.setToolTipText("");
        routeTrainTrainDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeTrainTrainDropActionPerformed(evt);
            }
        });

        routeTrainLineDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Line" }));

        routeTrainSectionDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Section" }));

        routeTrainSubmitButton.setText("Submit");

        routeTrainSpeedLabel.setText("Speed:");
        routeTrainSpeedLabel.setToolTipText("");

        javax.swing.GroupLayout routeTrainPanelLayout = new javax.swing.GroupLayout(routeTrainPanel);
        routeTrainPanel.setLayout(routeTrainPanelLayout);
        routeTrainPanelLayout.setHorizontalGroup(
            routeTrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(routeTrainPanelLayout.createSequentialGroup()
                .addGroup(routeTrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(routeTrainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(routeTrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(routeTrainTrainDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(routeTrainSectionDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(routeTrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(routeTrainLineDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(routeTrainsBlockDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(routeTrainPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(routeTrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(routeTrainPanelLayout.createSequentialGroup()
                                .addComponent(routeTrainAuthorityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(routeTrainAuthorityValueLabel))
                            .addGroup(routeTrainPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(routeTrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(routeTrainSubmitButton)
                                    .addGroup(routeTrainPanelLayout.createSequentialGroup()
                                        .addComponent(routeTrainSpeedLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(routeTrainSpeedText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(routeTrainPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(routeTrainLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        routeTrainPanelLayout.setVerticalGroup(
            routeTrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(routeTrainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(routeTrainLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(routeTrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routeTrainTrainDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(routeTrainLineDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(routeTrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routeTrainSectionDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(routeTrainsBlockDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(routeTrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routeTrainAuthorityValueLabel)
                    .addComponent(routeTrainAuthorityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(routeTrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routeTrainSpeedLabel)
                    .addComponent(routeTrainSpeedText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(routeTrainSubmitButton)
                .addGap(28, 28, 28))
        );

        switchPositionsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        switchPositionSubmitButton.setText("Submit");

        switchPositionLineDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Line", "Gree", "Red" }));
        switchPositionLineDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchPositionLineDropActionPerformed(evt);
            }
        });

        switchPositionSwitchesDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Switches" }));

        switchPositionRadioGroup.add(switchPositionsDivergentRadio);
        switchPositionsDivergentRadio.setText("Divergent");
        switchPositionsDivergentRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchPositionsDivergentRadioActionPerformed(evt);
            }
        });

        switchPositionLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        switchPositionLabel.setText("Switch Positions");

        switchPositionRadioGroup.add(switchPositionsStraightRadio);
        switchPositionsStraightRadio.setText("Straight");

        javax.swing.GroupLayout switchPositionsPanelLayout = new javax.swing.GroupLayout(switchPositionsPanel);
        switchPositionsPanel.setLayout(switchPositionsPanelLayout);
        switchPositionsPanelLayout.setHorizontalGroup(
            switchPositionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, switchPositionsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(switchPositionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(switchPositionsPanelLayout.createSequentialGroup()
                        .addComponent(switchPositionLineDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(switchPositionSwitchesDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(switchPositionsPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(switchPositionLabel))
                    .addGroup(switchPositionsPanelLayout.createSequentialGroup()
                        .addComponent(switchPositionsDivergentRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(switchPositionsStraightRadio)))
                .addGap(25, 25, 25))
            .addGroup(switchPositionsPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(switchPositionSubmitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        switchPositionsPanelLayout.setVerticalGroup(
            switchPositionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, switchPositionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(switchPositionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(switchPositionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(switchPositionSwitchesDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(switchPositionLineDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(switchPositionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(switchPositionsDivergentRadio)
                    .addComponent(switchPositionsStraightRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(switchPositionSubmitButton)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(blockClosingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(routeTrainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(switchPositionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blockClosingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(routeTrainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(switchPositionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void blockClosingsLineDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockClosingsLineDropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blockClosingsLineDropActionPerformed

    private void routeTrainTrainDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeTrainTrainDropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routeTrainTrainDropActionPerformed

    private void routeTrainSpeedTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeTrainSpeedTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routeTrainSpeedTextActionPerformed

    private void switchPositionLineDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchPositionLineDropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_switchPositionLineDropActionPerformed

    private void switchPositionsDivergentRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchPositionsDivergentRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_switchPositionsDivergentRadioActionPerformed

    private void disableManualFunctions()
    {
        
        //Disable all the buttons and drop down menus in the Block Closing section
        this.blockClosingsSubmitButton.setEnabled(false);
        this.blockClosingsLineDrop.setEnabled(false);
        this.blockClosingsSectionDrop.setEnabled(false);
        this.blockClosingsBlockDrop.setEnabled(false);
        this.blockClosingsOpenRadio.setEnabled(false);
        this.blockClosingsCloseRadio.setEnabled(false);
        
        //Disable all the buttons and drop down menus in the Route Train section
        this.routeTrainSubmitButton.setEnabled(false);
        this.routeTrainSpeedText.setEnabled(false);
        this.routeTrainsBlockDrop.setEnabled(false);
        this.routeTrainSectionDrop.setEnabled(false);
        this.routeTrainTrainDrop.setEnabled(false);
        this.routeTrainLineDrop.setEnabled(false);
        
        //Disable all the buttons and drop down menus in the Change Switch Position section
        this.switchPositionSubmitButton.setEnabled(false);
        this.switchPositionsStraightRadio.setEnabled(false);
        this.switchPositionsDivergentRadio.setEnabled(false);
        this.switchPositionSwitchesDrop.setEnabled(false);
        this.switchPositionLineDrop.setEnabled(false);

        
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox blockClosingsBlockDrop;
    private javax.swing.JRadioButton blockClosingsCloseRadio;
    private javax.swing.JLabel blockClosingsLabel;
    private javax.swing.JComboBox blockClosingsLineDrop;
    private javax.swing.JRadioButton blockClosingsOpenRadio;
    private javax.swing.JPanel blockClosingsPanel;
    private javax.swing.ButtonGroup blockClosingsRadioGroup;
    private javax.swing.JComboBox blockClosingsSectionDrop;
    private javax.swing.JButton blockClosingsSubmitButton;
    private javax.swing.JLabel routeTrainAuthorityLabel;
    private javax.swing.JLabel routeTrainAuthorityValueLabel;
    private javax.swing.JLabel routeTrainLabel;
    private javax.swing.JComboBox routeTrainLineDrop;
    private javax.swing.JPanel routeTrainPanel;
    private javax.swing.JComboBox routeTrainSectionDrop;
    private javax.swing.JLabel routeTrainSpeedLabel;
    private javax.swing.JTextField routeTrainSpeedText;
    private javax.swing.JButton routeTrainSubmitButton;
    private javax.swing.JComboBox routeTrainTrainDrop;
    private javax.swing.JComboBox routeTrainsBlockDrop;
    private javax.swing.JLabel switchPositionLabel;
    private javax.swing.JComboBox switchPositionLineDrop;
    private javax.swing.ButtonGroup switchPositionRadioGroup;
    private javax.swing.JButton switchPositionSubmitButton;
    private javax.swing.JComboBox switchPositionSwitchesDrop;
    private javax.swing.JRadioButton switchPositionsDivergentRadio;
    private javax.swing.JPanel switchPositionsPanel;
    private javax.swing.JRadioButton switchPositionsStraightRadio;
    // End of variables declaration//GEN-END:variables
}
