/******************************************************************************
 * 
 * Tables class
 * 
 * Developed by AJility
 * April 2014
 * 
 * Contributers:
 *  Michael Kudlaty
 * 
 * DISCLAIMER:
 *   This document contains un-editable code generated by NetBeans.  Due to this
 *  un-editable code, this document does not follow the AJility coding standard.
 *
 *****************************************************************************/

package GUILayer.CTC;
import DataLayer.CTC.*;
import java.util.ArrayList;

public class Tables extends javax.swing.JPanel {

    /**
     * Creates new form Tables
     */
    public Tables() 
    {
        initComponents();
        this.trainDestinationTable.setAutoCreateColumnsFromModel(false); 
        this.trainLocationsTable.setAutoCreateColumnsFromModel(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        trainDestinationTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        trainLocationsTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        blockClosingsTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        switchPositionsTable = new javax.swing.JTable();
        trainDestinationLabel = new javax.swing.JLabel();
        blockClosingsLabel = new javax.swing.JLabel();
        switchPositionsLabel = new javax.swing.JLabel();
        trainLocationsLabel = new javax.swing.JLabel();

        trainDestinationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Train", "Line", "Section", "Block", "Station"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(trainDestinationTable);

        trainLocationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Train", "Authority", "Line", "Section", "Block", "Station"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(trainLocationsTable);

        blockClosingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Line", "Block ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(blockClosingsTable);

        switchPositionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Line", "Switch ID", "Block:Block", "Position"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(switchPositionsTable);

        trainDestinationLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        trainDestinationLabel.setText("Train Destination");

        blockClosingsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        blockClosingsLabel.setText("Block Closings");

        switchPositionsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        switchPositionsLabel.setText("Switch Positions");

        trainLocationsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        trainLocationsLabel.setText("Train Locations");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(switchPositionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blockClosingsLabel)
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(trainLocationsLabel)
                        .addGap(260, 260, 260))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(trainDestinationLabel)
                        .addGap(252, 252, 252))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trainLocationsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(trainDestinationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(switchPositionsLabel)
                    .addComponent(blockClosingsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void SetTrainLocations(ArrayList<TrainsClass> trains)
    {
        for(int i = 0; i <trains.size(); i++)
        {
            this.trainLocationsTable.setValueAt(Integer.toString(i), i, 0);
            this.trainLocationsTable.setValueAt(Integer.toString(trains.get(i).Authority), i, 1);
            this.trainLocationsTable.setValueAt(trains.get(i).lineColor(), i, 2);
            this.trainLocationsTable.setValueAt(trains.get(i).SectionCurrent, i, 3);
            this.trainLocationsTable.setValueAt(trains.get(i).BlockCurrent, i, 4);
            this.trainLocationsTable.setValueAt(trains.get(i).StationCurrent, i, 5);
            
        }
    }
    
    public void SetTrainDestination(ArrayList<TrainsClass> trains)
    {
        for(int i = 0; i <trains.size(); i++)
        {
            this.trainDestinationTable.setValueAt(Integer.toString(i), i, 0);
            this.trainDestinationTable.setValueAt(trains.get(i).lineColor(), i , 1);
            this.trainDestinationTable.setValueAt(trains.get(i).SectionDestination, i, 2);
            this.trainDestinationTable.setValueAt(trains.get(i).BlockDestination, i, 3);
            this.trainDestinationTable.setValueAt(trains.get(i).StationDestination, i, 4);            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blockClosingsLabel;
    private javax.swing.JTable blockClosingsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel switchPositionsLabel;
    private javax.swing.JTable switchPositionsTable;
    private javax.swing.JLabel trainDestinationLabel;
    private javax.swing.JTable trainDestinationTable;
    private javax.swing.JLabel trainLocationsLabel;
    private javax.swing.JTable trainLocationsTable;
    // End of variables declaration//GEN-END:variables
}
